<?php

/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-plugin/basic-adsense/qa-basic-adsense.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Widget module class for AdSense widget plugin


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	class  qa_html_theme_layer extends qa_html_theme_base {
		
		function head_css()
        {
            $this->content['css_src'][]=qa_html(QA_HTML_THEME_LAYER_URLTOROOT.'node_modules/slick-carousel/slick/slick.css');
            $this->content['css_src'][]=qa_html(QA_HTML_THEME_LAYER_URLTOROOT.'node_modules/slick-carousel/slick/slick-theme.css');
            $this->content['css_src'][]=qa_html(QA_HTML_THEME_LAYER_URLTOROOT.'css/slider.css');
            parent::head_css(); // TODO: Change the autogenerated stub
        }
        function head_script()
        {
            $this->content['script'][]='<script type="text/javascript" src="'.QA_HTML_THEME_LAYER_URLTOROOT.'node_modules/slick-carousel/slick/slick.min.js"></script> ';
            $this->content['script'][]='<script type="text/javascript">$("#slicker").slick({rtl: true, dots: true, autoplay: true, arrows: true, slidesToShow: 1, slidesToScroll:1, autoplaySpeed: 5000})</script> ';
            parent::head_script(); // TODO: Change the autogenerated stub
        }
    }
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
